apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: ebank-skaffold
build:
  tagPolicy:
    dateTime: {}
  artifacts:
    - image: ghcr.io/MaxVelKir/ebank/ebank
      docker:
        dockerfile: Dockerfile
