apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: ebank-skaffold
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ghcr.io/maxvelkir/ebank/ebank
      docker:
        dockerfile: Dockerfile
