apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: ebank-skaffold
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: ghcr.io/maxvelkir/ebank/ebank
      context: apps/ebank
      docker:
        dockerfile: Dockerfile
    - image: ghcr.io/maxvelkir/ebank/ebank-web
      docker:
        dockerfile: Dockerfile

deploy:
  kubectl:
    manifests:
      - infra/secrets/registryauth.yaml
      - infra/ebank.yaml
      - infra/ebank_web.yaml
