apiVersion: v1
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2doY3IuaW8iOnsiYXV0aCI6IlRXRjRWbVZzUzJseU9tZG9jRjlJWVRaWU56Wm1ZME5rT1VScWIyMXlVV2RzY2xOYU4xUktjRzgxTlVVeU9VaGxXVzQ9IiwicGFzc3dvcmQiOiJnaHBfSGE2WDc2ZmNDZDlEam9tclFnbHJTWjdUSnBvNTVFMjlIZVluIiwidXNlcm5hbWUiOiJNYXhWZWxLaXIifX19

kind: Secret
metadata:
  name: dockerconfigjson-github-com
  namespace: default
