---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebank
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebank
  template:
    metadata:
      labels:
        app: ebank
    spec:
      containers:
        - name: ebank
          image: ghcr.io/maxvelkir/ebank/ebank

      imagePullSecrets:
        - name: dockerconfigjson-github-com
