---
name: Create and publish a Docker image

on:
  push:
    branches:
      - master

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log into ghcr
        run: |
          echo ${{ secrets.GH_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Skaffold run
        uses: hiberbee/github-action-skaffold@1.12.0
        with:
          command: build
